---
title: "Data Cleaning and Modeling"
author: "Matt Johnson"
date: "10/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
```

Import Data

```{r}
Game.Results = read.csv("GameResults.csv")
Game.Stats = read.csv("GameStats.csv")
Predictions = read.csv("Predictions.csv")
Rankings <- read.csv("Ranking.csv")
```

Cleaning

```{r}
Game.Stats$School <- as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "Miami (FL)"] <- "Miami"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "Miami (FL)"] <- "Miami"

Game.Stats$School <- as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "Miami (OH)"] <- "Miami Ohio"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "Miami (OH)"] <- "Miami Ohio"

Game.Results$Home.Team <- as.character(Game.Results$Home.Team)
Game.Results$Home.Team[Game.Results$Home.Team == "Miami Florida"] <- "Miami"

Game.Results$Visitor.Team <- as.character(Game.Results$Visitor.Team)
Game.Results$Visitor.Team[Game.Results$Visitor.Team == "Miami Florida"] <- "Miami"

Game.Stats$School <- as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "North Carolina State"] <- "NC State"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "North Carolina State"] <- "NC State"

Game.Stats$School <- as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "Florida International"] <- "FIU"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "Florida International"] <- "FIU"

Game.Results$Home.Team <- as.character(Game.Results$Home.Team)
Game.Results$Home.Team[Game.Results$Home.Team == "Florida Intl"] <- "FIU"

Game.Results$Visitor.Team <- as.character(Game.Results$Visitor.Team)
Game.Results$Visitor.Team[Game.Results$Visitor.Team == "Florida Intl"] <- "FIU"

Game.Stats$School <- as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "Pittsburgh"] <- "Pitt"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "Pittsburgh"] <- "Pitt"

Game.Results$Home.Team <- as.character(Game.Results$Home.Team)
Game.Results$Home.Team[Game.Results$Home.Team == "Pittsburgh"] <- "Pitt"

Game.Results$Visitor.Team <- as.character(Game.Results$Visitor.Team)
Game.Results$Visitor.Team[Game.Results$Visitor.Team == "Pittsburgh"] <- "Pitt"

no.mercer = subset(Game.Stats, Opponent != "Mercer")
no.alabamastate = subset(no.mercer, Opponent != "Alabama State")
Game.Stats = no.alabamastate

Game.Stats$School = as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "Akron"] <- "Mercer"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "Akron"] <- "Mercer"

Game.Results$Home.Team <- as.character(Game.Results$Home.Team)
Game.Results$Home.Team[Game.Results$Home.Team == "Akron"] <- "Mercer"

Game.Results$Visitor.Team <- as.character(Game.Results$Visitor.Team)
Game.Results$Visitor.Team[Game.Results$Visitor.Team == "Akron"] <- "Mercer"

Game.Stats$School = as.character(Game.Stats$School)
Game.Stats$School[Game.Stats$School == "UTSA"] <- "Alabama State"

Game.Stats$Opponent <- as.character(Game.Stats$Opponent)
Game.Stats$Opponent[Game.Stats$Opponent == "UTSA"] <- "Alabama State"

Game.Results$Home.Team <- as.character(Game.Results$Home.Team)
Game.Results$Home.Team[Game.Results$Home.Team == "UTSA"] <- "Alabama State"

Game.Results$Visitor.Team <- as.character(Game.Results$Visitor.Team)
Game.Results$Visitor.Team[Game.Results$Visitor.Team == "UTSA"] <- "Alabama State"

Game.Stats.Away <- Game.Stats %>% 
  filter(X == "@")
Game.Stats.Home <- Game.Stats %>% 
  filter(X == "")
#not sure what to do with this yet but we can figure it out also just realized there are no stats for mercer
Game.Stats.N <- Game.Stats %>% 
  filter(X == "N")

Game.Stats.Home.1 <-  Game.Stats.Home %>% 
  rename(Home.Team = School) %>% 
  rename(Visitor.Team = Opponent) %>% 
  select(c(-1, -4, -5))

Game.Stats.Away.1 <-  Game.Stats.Away %>% 
  rename(Visitor.Team = School) %>% 
  rename(Home.Team = Opponent) %>% 
  select(c(-1, -4, -5))
varname.away = 'Away'
names(Game.Stats.Away.1)[4:ncol(Game.Stats.Away.1)] <- paste0(rep(varname.away), "_", c(names(Game.Stats.Away.1[, 4:23])))
 
#this is fucked but this is how we need to get Alabama State Stats for 2019
Alabama.state.19 <- Game.Stats.Away.1 %>% 
  filter(Visitor.Team == "Alabama State")
Alabama.state.19 <- filter(Alabama.state.19, str_detect(Date, '2019'))
Alabama.state.data <- Alabama.state.19 %>% 
  group_by(Visitor.Team) %>% 
  summarise_all(list(Avg = mean)) %>% 
  select(-c(2:4))
Alabama.state.data[1, 13] <- 66
Alabama.state.data[1, 16] <- 50


varname.home <-  'Home'
Game.Stats.V2 <- full_join(Game.Stats.Home.1, Game.Stats.Away.1)
Game.Stats.V2[is.na(Game.Stats.V2)] <- 0
Game.Stats.V2 <- Game.Stats.V2 %>% 
  filter(!is.na(Away_X.1))
names(Game.Stats.V2)[4:23] <- paste0(rep(varname.home), "_", c(names(Game.Stats.Home.1[, 4:23])))

#Game.Results cleaning
Game.Results.V2 <- Game.Results %>% 
  select(c(1:5, 8, 9, 10))

Game.Data.V1 <- na.omit(left_join(Game.Stats.V2, Game.Results.V2))
```

```{r}
O.Stats17 = read_xlsx("2017OStats.xlsx", skip = 1)
D.Stats17 = read_xlsx("2017DStats.xlsx", skip = 1)

O.Rank17 = data.frame(O.Stats17$School, O.Stats17$O.Rank17)
colnames(O.Rank17)[colnames(O.Rank17)=="O.Stats17.School"] <- "Home.Team"
colnames(O.Rank17)[colnames(O.Rank17)=="O.Stats17.O.Rank17"] <- "Home.O.Rank"

D.Rank17 = data.frame(D.Stats17$School, D.Stats17$D.Rank17)
colnames(D.Rank17)[colnames(D.Rank17)=="D.Stats17.School"] <- "Home.Team"
colnames(D.Rank17)[colnames(D.Rank17)=="D.Stats17.D.Rank17"] <- "Home.D.Rank"

Data17 = filter(Game.Data.V1, str_detect(Date, '2017'))

join = left_join(Data17, O.Rank17)
join2 = left_join(join, D.Rank17)

colnames(O.Rank17)[colnames(O.Rank17)=="Home.Team"] <- "Visitor.Team"
colnames(O.Rank17)[colnames(O.Rank17)=="Home.O.Rank"] <- "Visitor.O.Rank"

colnames(D.Rank17)[colnames(D.Rank17)=="Home.Team"] <- "Visitor.Team"
colnames(D.Rank17)[colnames(D.Rank17)=="Home.D.Rank"] <- "Visitor.D.Rank"

join3 = left_join(join2, O.Rank17)
join4 = left_join(join3, D.Rank17)
```

```{r}
O.Stats18 = read_xlsx("2018OStats.xlsx", skip = 1)
D.Stats18 = read_xlsx("2018DStats.xlsx", skip = 1)

O.Rank18 = data.frame(O.Stats18$School, O.Stats18$O.Rank18)
colnames(O.Rank18)[colnames(O.Rank18)=="O.Stats18.School"] <- "Home.Team"
colnames(O.Rank18)[colnames(O.Rank18)=="O.Stats18.O.Rank18"] <- "Home.O.Rank"

D.Rank18 = data.frame(D.Stats18$School, D.Stats18$D.Rank18)
colnames(D.Rank18)[colnames(D.Rank18)=="D.Stats18.School"] <- "Home.Team"
colnames(D.Rank18)[colnames(D.Rank18)=="D.Stats18.D.Rank18"] <- "Home.D.Rank"

Data18 = filter(Game.Data.V1, str_detect(Date, '2018'))

join5 = left_join(Data18, O.Rank18)
join6 = left_join(join5, D.Rank18)

colnames(O.Rank18)[colnames(O.Rank18)=="Home.Team"] <- "Visitor.Team"
colnames(O.Rank18)[colnames(O.Rank18)=="Home.O.Rank"] <- "Visitor.O.Rank"

colnames(D.Rank18)[colnames(D.Rank18)=="Home.Team"] <- "Visitor.Team"
colnames(D.Rank18)[colnames(D.Rank18)=="Home.D.Rank"] <- "Visitor.D.Rank"

join7 = left_join(join6, O.Rank18)
join8 = left_join(join7, D.Rank18)

Game.Data.V2 = rbind(join4, join8)
#only team missing is Mercer for the predictions, still need to change Pitt in predictions data
write.csv(Game.Data.V2, file = "Final_Game_Data.csv")
```


Setting up data for predictions
```{r}
Data19 <-  filter(Game.Data.V1, str_detect(Date, '2019'))

Pred.data <- Data19[, -c(2, 23, 44:48)]
#no mercer, only one clemson game, may have to look into using games from 2018 and avg those in too.
Virginia.Home <- Pred.data %>% 
  filter(Home.Team == "Virginia") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Virginia.Away <- Pred.data %>% 
  filter(Visitor.Team == "Virginia") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Clemson.Home <- Pred.data %>% 
  filter(Home.Team == "Clemson") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Clemson.Away <- Pred.data %>% 
  filter(Visitor.Team == "Clemson") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Wake.Home <- Pred.data %>% 
  filter(Home.Team == "Wake Forest") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Wake.Away <- Pred.data %>% 
  filter(Visitor.Team == "Wake Forest") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Duke.Home <- Pred.data %>% 
  filter(Home.Team == "Duke") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Duke.Away <- Pred.data %>% 
  filter(Visitor.Team == "Duke") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Syracuse.Home <- Pred.data %>% 
  filter(Home.Team == "Syracuse") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Syracuse.Away <- Pred.data %>% 
  filter(Visitor.Team == "Syracuse") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Florida.State.Home <- Pred.data %>% 
  filter(Home.Team == "Florida State") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Florida.State.Away <- Pred.data %>% 
  filter(Visitor.Team == "Florida State") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Georgia.Tech.Home <- Pred.data %>% 
  filter(Home.Team == "Georgia Tech") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Georgia.Tech.Away <- Pred.data %>% 
  filter(Visitor.Team == "Georgia Tech") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Virginia.Tech.Home <- Pred.data %>% 
  filter(Home.Team == "Virginia Tech") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Virginia.Tech.Away <- Pred.data %>% 
  filter(Visitor.Team == "Virginia Tech") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

NC.State.Home <- Pred.data %>% 
  filter(Home.Team == "NC State") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

NC.State.Away <- Pred.data %>% 
  filter(Visitor.Team == "NC State") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Louisville.Home <- Pred.data %>% 
  filter(Home.Team == "Louisville") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Louisville.Away <- Pred.data %>% 
  filter(Visitor.Team == "Louisville") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Notre.Dame.Home <- Pred.data %>% 
  filter(Home.Team == "Notre Dame") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Notre.Dame.Away <- Pred.data %>% 
  filter(Visitor.Team == "Notre Dame") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Boston.College.Home <- Pred.data %>% 
  filter(Home.Team == "Boston College") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Boston.College.Away <- Pred.data %>% 
  filter(Visitor.Team == "Boston College") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

FIU.Home <- Pred.data %>% 
  filter(Home.Team == "FIU") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

FIU.Away <- Pred.data %>% 
  filter(Visitor.Team == "FIU") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Miami.Home <- Pred.data %>% 
  filter(Home.Team == "Miami") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Miami.Away <- Pred.data %>% 
  filter(Visitor.Team == "Miami") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

North.Carolina.Home <- Pred.data %>% 
  filter(Home.Team == "North Carolina") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

North.Carolina.Away <- Pred.data %>% 
  filter(Visitor.Team == "North Carolina") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Liberty.Home <- Pred.data %>% 
  filter(Home.Team == "Liberty") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Liberty.Away <- Pred.data %>% 
  filter(Visitor.Team == "Liberty") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Kentucky.Home <- Pred.data %>% 
  filter(Home.Team == "Kentucky") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Kentucky.Away <- Pred.data %>% 
  filter(Visitor.Team == "Kentucky") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Georgia.Away <- Pred.data %>% 
  filter(Visitor.Team == "Georgia") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

Georgia.Home <- Pred.data %>% 
  filter(Home.Team == "Georgia") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Pitt.Home <- Pred.data %>% 
  filter(Home.Team == "Pitt") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Pitt.Away <- Pred.data %>% 
  filter(Visitor.Team == "Pitt") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))

South.Carolina.Home <- Pred.data %>% 
  filter(Home.Team == "South Carolina") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Florida.Home <- Pred.data %>% 
  filter(Home.Team == "Florida") %>%
  group_by(Home.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 4:21))

Mercer.Away <- Pred.data %>% 
  filter(Visitor.Team == "Mercer") %>%
  group_by(Visitor.Team) %>%
  summarise_all(list(Avg = mean)) %>% 
  select(c(1, 23:41))
```

```{r}
Predictions$Visitor.Team <- as.character(Predictions$Visitor.Team)
Predictions$Home.Team <- as.character(Predictions$Home.Team)
Predictions$Visitor.Team[Predictions$Visitor.Team == "Pittsburgh"] <- "Pitt"
Predictions$Home.Team[Predictions$Home.Team == "Pittsburgh"] <- "Pitt"

AwayStats <- rbind(Clemson.Away, Duke.Away, FIU.Away, Florida.State.Away, Georgia.Tech.Away, Kentucky.Away, Liberty.Away, Louisville.Away, Miami.Away, NC.State.Away, North.Carolina.Away, Notre.Dame.Away, Syracuse.Away, Virginia.Away, Virginia.Tech.Away, Wake.Away, Boston.College.Away, Georgia.Away, Pitt.Away, Alabama.state.data, Mercer.Away)
AwayStats <- AwayStats[, -20]

AP <- left_join(Predictions, AwayStats, by = "Visitor.Team")

HomeStats <- rbind(Clemson.Home, Duke.Home, FIU.Home, Florida.State.Home, Georgia.Tech.Home, Kentucky.Home, Liberty.Home, Louisville.Home, Miami.Home, NC.State.Home, North.Carolina.Home, Notre.Dame.Home, Syracuse.Home, Virginia.Home, Virginia.Tech.Home, Wake.Home, Boston.College.Home, Georgia.Home, Pitt.Home, South.Carolina.Home, Florida.Home)

Predictions.test <- left_join(AP, HomeStats, by = "Home.Team")
names(Predictions.test) <- c("Date","Home.Team","Visitor.Team","Spread","Total","Result", "Away_PassCmp",   "Away_PassAtt",   "Away_PassPct",   "Away_PassYds",   "Away_PassTD",    "Away_RushAtt",  
 "Away_RushYds",   "Away_RushAvg",   "Away_RushTD",    "Away_XPM",      
"Away_XPA",       "Away_XPPercent", "Away_FGM",       "Away_FGA",      
 "Away_FGPercent", "Away_KickPts",   "Away_Fum",       "Away_Int",      
 "Home_PassCmp",   "Home_PassAtt",   "Home_PassPct",   "Home_PassYds",  
 "Home_PassTD",    "Home_RushAtt",   "Home_RushYds",   "Home_RushAvg",  
 "Home_RushTD",    "Home_XPM",       "Home_XPA",       "Home_XPPercent",
"Home_FGM",       "Home_FGA",       "Home_FGPercent", "Home_KickPts",  
 "Home_Fum",       "Home_Int"  )

Home.Rankings <- Rankings %>% 
  rename(Home.O.Rank = O.Rank) %>% 
  rename(Home.D.Rank = D.Rank) %>% 
  rename(Home.Team = School) %>% 
  select(c(2:4))
Home.Rankings$Home.Team = as.character(Home.Rankings$Home.Team)
Visitor.Rankings <- Rankings %>% 
  rename(Visitor.O.Rank = O.Rank) %>% 
  rename(Visitor.D.Rank = D.Rank) %>% 
  rename(Visitor.Team = School) %>% 
  select(c(2:4))
Visitor.Rankings$Visitor.Team = as.character(Visitor.Rankings$Visitor.Team)

Predictions.test.rank <- left_join(Predictions.test, Visitor.Rankings)
Predictions.with.rank <- left_join(Predictions.test.rank, Home.Rankings)

Predictions.with.rank$Home_balance <- Predictions.with.rank$Home_RushAtt/(Predictions.with.rank$Home_RushAtt + Predictions.with.rank$Home_PassAtt)
Predictions.with.rank$Away_balance <- Predictions.with.rank$Away_RushAtt/(Predictions.with.rank$Away_RushAtt + Predictions.with.rank$Away_PassAtt)

Predictions.with.rank$Visitor.O.Rank[Predictions.with.rank$Visitor.Team == "Alabama State"] <- 116
Predictions.with.rank$Visitor.D.Rank[Predictions.with.rank$Visitor.Team == "Alabama State"] <- 101
Predictions.with.rank$Visitor.O.Rank[Predictions.with.rank$Visitor.Team == "Mercer"] <- 130
Predictions.with.rank$Visitor.D.Rank[Predictions.with.rank$Visitor.Team == "Mercer"] <- 129

Predictions.with.rank$Visitor.O.Rank[Predictions.with.rank$Visitor.Team == "NC State"] <- 106
Predictions.with.rank$Visitor.D.Rank[Predictions.with.rank$Visitor.Team == "NC State"] <- 75
Predictions.with.rank$Home.O.Rank[Predictions.with.rank$Home.Team == "NC State"] <- 106
Predictions.with.rank$Home.D.Rank[Predictions.with.rank$Home.Team == "NC State"] <- 75

Predictions.with.rank$Visitor.O.Rank[Predictions.with.rank$Visitor.Team == "Miami"] <- 66
Predictions.with.rank$Visitor.D.Rank[Predictions.with.rank$Visitor.Team == "Miami"] <- 20

Predictions.with.rank$Visitor.O.Rank[Predictions.with.rank$Visitor.Team == "Louisville"] <- 49
Predictions.with.rank$Visitor.D.Rank[Predictions.with.rank$Visitor.Team == "Louisville"] <- 111

Predictions.with.rank$Home.O.Rank[Predictions.with.rank$Home.Team == "FIU"] <- 86
Predictions.with.rank$Home.D.Rank[Predictions.with.rank$Home.Team == "FIU"] <- 58
#write.csv(Predictions.with.rank, "Predictions_test.csv")
```

