---
title: "EDA"
author: "Daniel Barlow"
date: "November 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(randomForest)
df <- read.csv("Final_Game_Data.csv")
Predictions <- read.csv("Predictions.csv")
```

```{r}
df$Home_balance <- df$Home_RushAtt/(df$Home_RushAtt + df$Home_PassAtt)
df$Away_balance <- df$Away_RushAtt/(df$Away_RushAtt + df$Away_PassAtt)
df <- na.omit(df)
df$Home.Team <- as.character(df$Home.Team)
df$Visitor.Team <- as.character(df$Visitor.Team)
Predictions$Home.Team <- as.character(Predictions$Home.Team)
Predictions$Visitor.Team <- as.character(Predictions$Visitor.Team)
Predictions$Home.Team[Predictions$Home.Team == "Pittsburgh"] <- "Pitt"
Predictions$Visitor.Team[Predictions$Visitor.Team == "Pittsburgh"] <- "Pitt"
# df1 <- df %>% filter(Home.Team %in% Predictions$Home.Team | Home.Team %in% Predictions$Visitor.Team && Visitor.Team %in% Predictions$Home.Team | Visitor.Team %in% Predictions$Visitor.Team)
# df1$Date <- as.character.Date(df1$Date)
# df1 <- df1[ , c(-1, -3)]
# df1$Home.Team <- factor(df1$Home.Team)
# df1$Visitor.Team <- factor(df1$Visitor.Team)
```

```{r}
set.seed(1305)
size = floor(.7*nrow(df))
train.idx = sample(seq_len(nrow(df)), size = size)
train = df[train.idx, -c(1:4, 25, 45:49)] #takes out any variables that have characters associated to them as well as spread, home.score, visitor.score, total
test = df[-train.idx, -c(1:4, 25, 45:49)]
```

```{r}
mod1 = glm(Home_X.1 ~ ., data = train, family = "binomial", control = list(maxit = 50))

model = randomForest(x=dplyr::select(train,-Home_X.1),
                     y=as.factor(train$Home_X.1),
                     xtest=dplyr::select(test,-Home_X.1),
                     ytest=as.factor(test$Home_X.1),
                     type="classification")
importance(model)
#so obviously extra points mdae and attempted are clearly important because those are exac
```

